name: Lambda Runners
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-runners.yml
      - "modules/runners/lambdas/runners/**"
jobs:
  build:
    uses: ./.github/workflows/lambda-template.yml
    with:
      working-directory: modules/runners/lambdas/runners
