name: Lambda Runners
on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/lambda-runners.yml
      - "modules/runners/lambdas/runners/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    defaults:
      run:
        working-directory: modules/runners/lambdas/runners

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run prettier
        run: yarn format-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run two tests in isolation
        run: |
           yarn run test src/scale-runners/scale-up.test.ts -t 'scaleUp with GHES on org level creates a runner with labels in s specific group' --coverage=false
           yarn run test src/scale-runners/scale-up.test.ts -t 'scaleUp with public GH on org level creates a runner with labels in s specific group' --coverage=false
      - name: Build distribution
        run: yarn build
