name: "Terraform checks"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - "modules/*/lambdas/**"

env:
  AWS_REGION: eu-west-1
jobs:
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [1.1.3, 'latest']
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Fake zip files" # Validate will fail if it cannot find the zip files
        run: |
          touch modules/webhook/lambdas/webhook/webhook.zip
          touch modules/runners/lambdas/runners/runners.zip
          touch modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/runner-binaries-syncer.zip
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.1.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
      - if: contains(matrix.terraform, 'latest') # check formatting for the latest release but avoid failing the build
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        run: terraform validate

  verify_examples:
    name: Verify examples
    strategy:
      fail-fast: false
      matrix:
        terraform: [1.0.11, 1.1.3, 'latest']
        example: ["default", "ubuntu", "prebuilt", "arm64", "ephemeral", "windows"]
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v3
      - name: terraform init
        run: terraform init -get -backend=false -input=false
      - if: contains(matrix.terraform, '1.1.')
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
      - if: contains(matrix.terraform, 'latest') # check formatting for the latest release but avoid failing the build
        name: check terraform formatting
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform011
        run: terraform validate
